# DO NOT EDIT THIS FILE, IT SHOULD NOT NEED TO BE EDITED.
# ONLY EDIT environment.properties AND docker-compose.yml AND ONLY IF NEEDED.
# EXCEPT FOR download-and-run.sh IN THE server_files DIRECTORY, THAT FOLDER IS OTHERWISE ALSO FREE REIGN.

FROM openjdk16:alpine

# Update system
RUN apk update && apk add curl jq

# Set required vars -- DO NOT SET THESE, THEY ARE SET BY DOCKER COMPOSE
ENV VERSION="" BUILD="" RAM=""

# Move into correct directory and add script
WORKDIR /server_files
ADD /download-and-run.sh /download-and-run.sh

# Run the script with the env vars from docker-compose
CMD ["VERSION=$VERSION", "BUILD=$BUILD", "RAM=$RAM", "ash", "./download-and-run.sh"]
