# DO NOT EDIT THIS FILE, IT SHOULD NOT NEED TO BE EDITED.
# ONLY EDIT environment AND docker-compose.yml AND ONLY IF NEEDED.
# EXCEPT FOR download-and-run.sh IN THE server_files DIRECTORY, THAT FOLDER IS OTHERWISE ALSO FREE REIGN.
FROM adoptopenjdk/openjdk16:alpine-slim

# Update system
RUN apk update && apk add curl jq

# Set required vars -- DO NOT SET THESE, THEY ARE SET BY DOCKER COMPOSE
ENV VERSION=""
ENV BUILD=""
ENV RAM=""

# Move into correct directory
WORKDIR /server_files

# Run the script with the env vars from docker-compose
CMD /bin/sh -c "VERSION=$VERSION BUILD=$BUILD RAM=$RAM sh ./download-and-run.sh"
